<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>955c946f-fb34-47cb-9d12-240e4ad5e03f</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\AspireOrchestrator\AspireOrchestrator.ServiceDefaults\AspireOrchestrator.ServiceDefaults.csproj" />
      <ProjectReference Include="..\..\..\ChatBot.OpenAiFacade\ChatBot.OpenAiFacade.csproj" />
      <ProjectReference Include="..\ChatBot.Application\ChatBot.Application.csproj" />
      <ProjectReference Include="..\ChatBot.Contracts\ChatBot.Contracts.csproj" />
    </ItemGroup>

</Project>
