<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>87ba1c14-352d-431d-9b2c-835c9a2f90b2</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="8.0.1"/>
        <PackageReference Include="Aspire.Hosting.Azure.Sql" Version="8.0.1" />
        <PackageReference Include="Aspire.Hosting.NodeJs" Version="8.0.1" />
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="8.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ChatBot.MigrationService\ChatBot.MigrationService.csproj" />
      <ProjectReference Include="..\ChatBot\ChatBot.Api\ChatBot.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
