<Project Sdk="Microsoft.NET.Sdk;Aspire.AppHost.Sdk/9.0.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>87ba1c14-352d-431d-9b2c-835c9a2f90b2</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting" Version="9.1.0" />
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.1.0" />
        <PackageReference Include="Aspire.Hosting.Azure.Sql" Version="9.1.0" />
        <PackageReference Include="Aspire.Hosting.Kafka" Version="9.1.0" />
        <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.1.0" />
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="9.1.0" />
        <PackageReference Include="System.Runtime" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ChatBot.Categories\ChatBot.Categories.Api\ChatBot.Categories.Api.csproj" />
      <ProjectReference Include="..\ChatBot.Common\ChatBot.Common.csproj" />
      <ProjectReference Include="..\ChatBot.MigrationService\ChatBot.MigrationService.csproj" />
      <ProjectReference Include="..\ChatBot\ChatBot.Api\ChatBot.Api.csproj" />
      <ProjectReference Include="..\ChatBot.Users\ChatBot.Users.Api\ChatBot.Users.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configuration\Http\" />
      <Folder Include="Configuration\Kafka\" />
    </ItemGroup>
</Project>
